language: node_js
node_js:
- '16'
services:
- docker

notifications:
  email: false
  slack:
    rooms:
      secure: xMdLaZuz9OEJJ6i4ZGgW+kVsykYnTFCdh6eZNM1E1jF307WyM0Ja1CSBCAOxpZsLoXh5ZUorud4LScFco59LpPzBDTvhbLw0oaxBHXOiGF+z1QQ9AXWm4LwN+R9rnY0Rb7IhqhndVLRXATT0XI8pGhOPCkx4buJdKqn7fJISvY1TkPzbyVPuZb41kcF/+LMJTihBxa6JxgiAZIxzlv6OKFTB4XxBWmeYWPfUyPFbNJzYCFniny9Y5OliqL5djws6DvIz0ScYHApVTg6vWO2F+aXY6oEHgU9XpFA19DFpVysvp2fYPuxfSsEcllshHVUe331r0f8dMswDq8bBnfohNmj2B5fs+vFBLzRKX1dtKSBIO/AEa8lqgbR85dwP6G5f3mDqHMU5YJVD43wkI9xqBoJAySfvz1juUMicRAb+dRTCcvP+D9vEjkPdRMhsNiVJCUQlEy+yN7c0A/rC93dzKVNf5dqs/uDb1CRrFTbWnJPS1GTurHau+q444P9RpZw52lvG8oYZtoCNL9d+ZR3yik6DCxk+a+BZUZ5Zt0R4SLeie+IaSKYmFcWHAB+ss5EfNK5IWJ14oOIpSWi1lf6hoeRzt8dTVXkeFNWYeOXfgfkskfVIkx3azNR7km4nS2sqVrhwrjivN3VNQLphI56eWmIBCyuH3He6lDH/CQq6H74=
    on_success: always
    on_failure: always

before_script:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"

script:
- |
  IMAGE_NAME="kalisio/kdk-keycloak-theme"
  if [[ -z "$TRAVIS_TAG" ]]; then
    IMAGE_TAG=latest
  else
    IMAGE_TAG=$(node -p -e "require('./package.json').version")
  fi
  echo Building $IMAGE_NAME:$IMAGE_TAG
  docker build -t $IMAGE_NAME:$IMAGE_TAG .

deploy:
  provider: script
  script: docker push $IMAGE_NAME:$IMAGE_TAG
  on:
    all_branches: true
